spring:
  datasource:
    url: jdbc:h2:mem:antonio_prova
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  h2:
   console:
     enabled: true

fileRepositoryFolder: C:\\Users\\*****\\OneDrive\\Desktop\\FileRepository
